name: ci-test

on: [push, pull_request]

jobs:
  clj-test:
    # ubuntu 18.04 comes with lein + java8 installed
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Tests
        run:
          lein kaocha

  cljs-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Chrome
        run: |
          whoami
          sudo apt-get update -qq
          sudo apt-get install -q -y xvfb libgbm1 libxss1 chromium-browser

      - name: Ensure chrome installed
        run: chromium-browser --version

      - name: Cache node deps
        uses: actions/cache@v2
        id: cache-node-deps
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('package.json') }}

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.16.1

      - name: Fetch node deps
        if: steps.cache-node-deps.outputs.cache-hit != 'true'
        run: |
          pnpm install --shamefully-hoist

      - name: Run CLJS Tests
        run: |
          pnpm ci-build
          pnpm ci-test
